# This is a basic workflow that is manually triggered

name: Test conversion of study to cBioPortalData MultiAssayExperiment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Study to test'
        # Default value if no value is explicitly provided
        default: 'acc_tcga'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  test_study_conversion_to_mae:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 'Checkout git repo'
      uses: actions/checkout@v2
      with:
        lfs: true
    # Runs a single command using the runners shell
    - name: Test study converstion to MultiAssayExperiment
      
      uses: docker://inodb/cbioportaldata:split-cbiodatapack-function
      with:
        args: Rscript --vanilla -e 'library(cBioPortalData); source("/app/R/cBioDataPack.R"); source("/app/R/utils.R");loadStudy("./public/acc_tcga")'
        # run: echo "Hello ${{ github.event.inputs.name }}"
